sliders=GLINT_STRENGTH VHS_SATURATION VHS_SHARPEN VHS_LUMA_XRES VHS_CHROMA_XRES VHS_BOTH_YRES VHS_LUMA_NOISE VHS_CHROMA_NOISE
oldLighting=DIRECTIONAL_BLOCK_LIGHT
vignette=true

profile.DEFAULT=WORLD_FOG:true CLOUD_FOG:true SKY_FOG:true DIRECTIONAL_ENTITY_LIGHT:true DIRECTIONAL_BLOCK_LIGHT:true BLOCK_LIGHT_BRIGHTNESS_FIX:false GLINT_STRENGTH:0.75 MIPMAP_TYPE:0 VHS_CUTOFF:0.005 VHS_SATURATION:0.6 VHS_SHARPEN:0.3 VHS_LUMA_XRES:0.333 VHS_CHROMA_XRES:0.040 VHS_BOTH_YRES:0.5 VHS_LUMA_NOISE:0.02 VHS_CHROMA_NOISE:0.01

screen=<profile> [BASE_OPTS] <empty> <empty> VHS_CUTOFF VHS_SATURATION VHS_SHARPEN <empty> <empty> <empty> VHS_LUMA_XRES VHS_CHROMA_XRES VHS_BOTH_YRES <empty> <empty> <empty> VHS_LUMA_NOISE VHS_CHROMA_NOISE
screen.BASE_OPTS=WORLD_FOG CLOUD_FOG SKY_FOG DIRECTIONAL_ENTITY_LIGHT DIRECTIONAL_BLOCK_LIGHT BLOCK_LIGHT_BRIGHTNESS_FIX GLINT_STRENGTH MIPMAP_TYPE
